# Generated by Django 6.0 on 2026-01-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('ammonia', models.FloatField()),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'sensor_data',
            },
        ),
    ]
