# Generated by Django 6.0 on 2026-01-04 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartDecision', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='传感器名称')),
                ('sensor_type', models.CharField(choices=[('TEMP', '温度传感器'), ('HUMI', '湿度传感器'), ('CO2', '二氧化碳传感器'), ('NH3', '氨气传感器'), ('WATT', '能耗传感器')], default='TEMP', max_length=10, verbose_name='传感器类型')),
                ('location', models.CharField(max_length=100, verbose_name='安装区域(如: 1号猪舍/A区)')),
                ('unit', models.CharField(max_length=20, verbose_name='计量单位(如: ℃, %, ppm)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_name_snapshot', models.CharField(max_length=100, verbose_name='传感器名称快照')),
                ('value', models.FloatField(verbose_name='监测数值')),
                ('timestamp', models.DateTimeField(verbose_name='监测时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='smartDecision.sensor')),
            ],
            options={
                'verbose_name': '传感器读数',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
